language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install -y gfortran
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py install --with_pdd
script:
  - pytest --cov=solcore/
after_success:
  - coveralls
